/**
 * Bootstrap Builder - Complete Component Library
 * All Bootstrap 5.3 Components
 */
const COMPONENTS = {
    layout: {
        name: 'Layout', icon: 'bi-grid-1x2',
        items: [
            { id: 'container', name: 'Container', icon: 'bi-box', html: '<div class="container py-4"><p class="text-muted">Container - Add content here</p></div>' },
            { id: 'container-fluid', name: 'Full Width', icon: 'bi-arrows-fullscreen', html: '<div class="container-fluid py-4 bg-light"><p class="text-muted">Full Width Container</p></div>' },
            { id: 'row-2col', name: '2 Columns', icon: 'bi-layout-split', html: '<div class="container py-4"><div class="row"><div class="col-md-6"><div class="p-3 border rounded bg-light">Column 1</div></div><div class="col-md-6"><div class="p-3 border rounded bg-light">Column 2</div></div></div></div>' },
            { id: 'row-3col', name: '3 Columns', icon: 'bi-layout-three-columns', html: '<div class="container py-4"><div class="row"><div class="col-md-4"><div class="p-3 border rounded bg-light">Col 1</div></div><div class="col-md-4"><div class="p-3 border rounded bg-light">Col 2</div></div><div class="col-md-4"><div class="p-3 border rounded bg-light">Col 3</div></div></div></div>' },
            { id: 'row-4col', name: '4 Columns', icon: 'bi-grid', html: '<div class="container py-4"><div class="row"><div class="col-md-3"><div class="p-3 border rounded bg-light">Col 1</div></div><div class="col-md-3"><div class="p-3 border rounded bg-light">Col 2</div></div><div class="col-md-3"><div class="p-3 border rounded bg-light">Col 3</div></div><div class="col-md-3"><div class="p-3 border rounded bg-light">Col 4</div></div></div></div>' },
            { id: 'row-sidebar', name: 'Sidebar Layout', icon: 'bi-layout-sidebar', html: '<div class="container py-4"><div class="row"><div class="col-md-3"><div class="p-3 border rounded bg-light">Sidebar</div></div><div class="col-md-9"><div class="p-3 border rounded bg-light">Main Content</div></div></div></div>' },
            { id: 'section', name: 'Section', icon: 'bi-square', html: '<section class="py-5"><div class="container"><h2>Section Title</h2><p class="lead text-muted">Add your section content here.</p></div></section>' },
            { id: 'divider', name: 'Divider', icon: 'bi-dash-lg', html: '<div class="container"><hr class="my-4"></div>' }
        ]
    },
    navigation: {
        name: 'Navigation', icon: 'bi-list',
        items: [
            { id: 'navbar-dark', name: 'Navbar Dark', icon: 'bi-menu-button-wide', html: '<nav class="navbar navbar-expand-lg navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="#">Brand</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navDark"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navDark"><ul class="navbar-nav ms-auto"><li class="nav-item"><a class="nav-link active" href="#">Home</a></li><li class="nav-item"><a class="nav-link" href="#">Features</a></li><li class="nav-item"><a class="nav-link" href="#">Pricing</a></li></ul></div></div></nav>' },
            { id: 'navbar-light', name: 'Navbar Light', icon: 'bi-menu-button', html: '<nav class="navbar navbar-expand-lg navbar-light bg-light"><div class="container"><a class="navbar-brand" href="#">Brand</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navLight"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navLight"><ul class="navbar-nav ms-auto"><li class="nav-item"><a class="nav-link active" href="#">Home</a></li><li class="nav-item"><a class="nav-link" href="#">About</a></li></ul></div></div></nav>' },
            { id: 'navbar-primary', name: 'Navbar Primary', icon: 'bi-menu-app', html: '<nav class="navbar navbar-expand-lg navbar-dark bg-primary"><div class="container"><a class="navbar-brand" href="#">Brand</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navPrimary"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navPrimary"><ul class="navbar-nav ms-auto"><li class="nav-item"><a class="nav-link active" href="#">Home</a></li><li class="nav-item"><a class="nav-link" href="#">About</a></li></ul></div></div></nav>' },
            { id: 'nav-pills', name: 'Nav Pills', icon: 'bi-segmented-nav', html: '<div class="container py-3"><ul class="nav nav-pills"><li class="nav-item"><a class="nav-link active" href="#">Active</a></li><li class="nav-item"><a class="nav-link" href="#">Link</a></li><li class="nav-item"><a class="nav-link" href="#">Link</a></li><li class="nav-item"><a class="nav-link disabled">Disabled</a></li></ul></div>' },
            { id: 'nav-tabs', name: 'Nav Tabs', icon: 'bi-folder', html: '<div class="container py-3"><ul class="nav nav-tabs"><li class="nav-item"><a class="nav-link active" href="#">Active</a></li><li class="nav-item"><a class="nav-link" href="#">Link</a></li><li class="nav-item"><a class="nav-link" href="#">Link</a></li><li class="nav-item"><a class="nav-link disabled">Disabled</a></li></ul></div>' },
            { id: 'breadcrumb', name: 'Breadcrumb', icon: 'bi-chevron-right', html: '<nav aria-label="breadcrumb" class="py-3"><div class="container"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="#">Home</a></li><li class="breadcrumb-item"><a href="#">Category</a></li><li class="breadcrumb-item active">Current</li></ol></div></nav>' },
            { id: 'pagination', name: 'Pagination', icon: 'bi-three-dots', html: '<nav class="py-3"><div class="container"><ul class="pagination justify-content-center"><li class="page-item disabled"><a class="page-link" href="#">«</a></li><li class="page-item active"><a class="page-link" href="#">1</a></li><li class="page-item"><a class="page-link" href="#">2</a></li><li class="page-item"><a class="page-link" href="#">3</a></li><li class="page-item"><a class="page-link" href="#">»</a></li></ul></div></nav>' },
            { id: 'pagination-lg', name: 'Pagination Large', icon: 'bi-123', html: '<nav class="py-3"><div class="container"><ul class="pagination pagination-lg justify-content-center"><li class="page-item active"><a class="page-link" href="#">1</a></li><li class="page-item"><a class="page-link" href="#">2</a></li><li class="page-item"><a class="page-link" href="#">3</a></li></ul></div></nav>' }
        ]
    },
    typography: {
        name: 'Typography', icon: 'bi-fonts',
        items: [
            { id: 'heading-h1', name: 'Heading H1', icon: 'bi-type-h1', html: '<div class="container py-3"><h1>Heading 1</h1></div>' },
            { id: 'heading-h2', name: 'Heading H2', icon: 'bi-type-h2', html: '<div class="container py-3"><h2>Heading 2</h2></div>' },
            { id: 'heading-h3', name: 'Heading H3', icon: 'bi-type-h3', html: '<div class="container py-3"><h3>Heading 3</h3></div>' },
            { id: 'display-1', name: 'Display 1', icon: 'bi-type-bold', html: '<div class="container py-3"><h1 class="display-1">Display 1</h1></div>' },
            { id: 'display-4', name: 'Display 4', icon: 'bi-type', html: '<div class="container py-3"><h1 class="display-4">Display 4</h1></div>' },
            { id: 'lead', name: 'Lead Text', icon: 'bi-text-paragraph', html: '<div class="container py-3"><p class="lead">This is a lead paragraph. It stands out from regular paragraphs.</p></div>' },
            { id: 'paragraph', name: 'Paragraph', icon: 'bi-justify', html: '<div class="container py-3"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div>' },
            { id: 'blockquote', name: 'Blockquote', icon: 'bi-quote', html: '<div class="container py-3"><figure><blockquote class="blockquote"><p>A well-known quote, contained in a blockquote element.</p></blockquote><figcaption class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></figcaption></figure></div>' },
            { id: 'text-muted', name: 'Muted Text', icon: 'bi-type-strikethrough', html: '<div class="container py-3"><p class="text-muted">This text is muted and less prominent.</p></div>' },
            { id: 'list-unstyled', name: 'List Unstyled', icon: 'bi-list-ul', html: '<div class="container py-3"><ul class="list-unstyled"><li>Item one</li><li>Item two</li><li>Item three</li></ul></div>' },
            { id: 'list-inline', name: 'List Inline', icon: 'bi-list-nested', html: '<div class="container py-3"><ul class="list-inline"><li class="list-inline-item">Item 1</li><li class="list-inline-item">Item 2</li><li class="list-inline-item">Item 3</li></ul></div>' }
        ]
    },
    content: {
        name: 'Content', icon: 'bi-file-text',
        items: [
            { id: 'image', name: 'Image', icon: 'bi-image', html: '<div class="container py-3"><img src="https://picsum.photos/800/400" class="img-fluid rounded" alt="Image"></div>' },
            { id: 'image-thumbnail', name: 'Thumbnail', icon: 'bi-image-alt', html: '<div class="container py-3"><img src="https://picsum.photos/200/200" class="img-thumbnail" alt="Thumbnail"></div>' },
            { id: 'figure', name: 'Figure', icon: 'bi-file-image', html: '<div class="container py-3"><figure class="figure"><img src="https://picsum.photos/400/300" class="figure-img img-fluid rounded" alt="Figure"><figcaption class="figure-caption">A caption for the above image.</figcaption></figure></div>' },
            { id: 'table', name: 'Table', icon: 'bi-table', html: '<div class="container py-3"><table class="table"><thead><tr><th>#</th><th>Name</th><th>Email</th></tr></thead><tbody><tr><td>1</td><td>John Doe</td><td>john@example.com</td></tr><tr><td>2</td><td>Jane Smith</td><td>jane@example.com</td></tr></tbody></table></div>' },
            { id: 'table-striped', name: 'Table Striped', icon: 'bi-table', html: '<div class="container py-3"><table class="table table-striped table-hover"><thead class="table-dark"><tr><th>#</th><th>Name</th><th>Status</th></tr></thead><tbody><tr><td>1</td><td>John</td><td><span class="badge bg-success">Active</span></td></tr><tr><td>2</td><td>Jane</td><td><span class="badge bg-warning">Pending</span></td></tr></tbody></table></div>' },
            { id: 'table-bordered', name: 'Table Bordered', icon: 'bi-grid-3x3', html: '<div class="container py-3"><table class="table table-bordered"><thead><tr><th>#</th><th>Name</th><th>Email</th></tr></thead><tbody><tr><td>1</td><td>John</td><td>john@example.com</td></tr></tbody></table></div>' }
        ]
    },
    cards: {
        name: 'Cards', icon: 'bi-card-text',
        items: [
            { id: 'card-basic', name: 'Card Basic', icon: 'bi-card-heading', html: '<div class="container py-3"><div class="card" style="width: 18rem;"><div class="card-body"><h5 class="card-title">Card title</h5><p class="card-text">Some quick example text to build on the card title.</p><a href="#" class="btn btn-primary">Go somewhere</a></div></div></div>' },
            { id: 'card-image', name: 'Card Image', icon: 'bi-card-image', html: '<div class="container py-3"><div class="card" style="width: 18rem;"><img src="https://picsum.photos/286/180" class="card-img-top" alt="Card image"><div class="card-body"><h5 class="card-title">Card title</h5><p class="card-text">Some text to support the card.</p><a href="#" class="btn btn-primary">Button</a></div></div></div>' },
            { id: 'card-horizontal', name: 'Card Horizontal', icon: 'bi-card-list', html: '<div class="container py-3"><div class="card mb-3" style="max-width: 540px;"><div class="row g-0"><div class="col-md-4"><img src="https://picsum.photos/180/250" class="img-fluid rounded-start" alt="Image"></div><div class="col-md-8"><div class="card-body"><h5 class="card-title">Card title</h5><p class="card-text">This is a wider card with supporting text.</p><p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p></div></div></div></div></div>' },
            { id: 'card-group', name: 'Card Group', icon: 'bi-collection', html: '<div class="container py-4"><div class="row row-cols-1 row-cols-md-3 g-4"><div class="col"><div class="card h-100"><img src="https://picsum.photos/300/200" class="card-img-top" alt="Card 1"><div class="card-body"><h5 class="card-title">Card 1</h5><p class="card-text">Description.</p></div></div></div><div class="col"><div class="card h-100"><img src="https://picsum.photos/300/200" class="card-img-top" alt="Card 2"><div class="card-body"><h5 class="card-title">Card 2</h5><p class="card-text">Description.</p></div></div></div><div class="col"><div class="card h-100"><img src="https://picsum.photos/300/200" class="card-img-top" alt="Card 3"><div class="card-body"><h5 class="card-title">Card 3</h5><p class="card-text">Description.</p></div></div></div></div></div>' },
            { id: 'card-header', name: 'Card Header', icon: 'bi-window-plus', html: '<div class="container py-3"><div class="card"><div class="card-header">Featured</div><div class="card-body"><h5 class="card-title">Special title</h5><p class="card-text">With supporting text below.</p><a href="#" class="btn btn-primary">Go somewhere</a></div></div></div>' },
            { id: 'card-footer', name: 'Card with Footer', icon: 'bi-window-dock', html: '<div class="container py-3"><div class="card text-center"><div class="card-header">Featured</div><div class="card-body"><h5 class="card-title">Title</h5><p class="card-text">Some text.</p><a href="#" class="btn btn-primary">Button</a></div><div class="card-footer text-muted">2 days ago</div></div></div>' }
        ]
    },
    hero: {
        name: 'Hero Sections', icon: 'bi-stars',
        items: [
            { id: 'hero-simple', name: 'Hero Simple', icon: 'bi-layout-wtf', html: '<section class="bg-primary text-white py-5"><div class="container py-5"><div class="row align-items-center"><div class="col-lg-6"><h1 class="display-4 fw-bold mb-4">Build Amazing</h1><p class="lead mb-4">Create beautiful websites with Bootstrap 5.</p><a href="#" class="btn btn-light btn-lg">Get Started</a></div><div class="col-lg-6 text-center"><img src="https://picsum.photos/450/350" class="img-fluid rounded shadow" alt="Hero"></div></div></div></section>' },
            { id: 'hero-center', name: 'Hero Center', icon: 'bi-align-center', html: '<section class="bg-dark text-white py-5"><div class="container py-5 text-center"><h1 class="display-3 fw-bold mb-4">Welcome</h1><p class="lead mb-4 mx-auto" style="max-width: 600px;">Build your dream project.</p><a href="#" class="btn btn-primary btn-lg">Start Free</a></div></section>' },
            { id: 'hero-gradient', name: 'Hero Gradient', icon: 'bi-palette', html: '<section class="py-5" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"><div class="container py-5 text-center text-white"><h1 class="display-4 fw-bold mb-4">Beautiful Gradient</h1><p class="lead mb-4">Make your site stand out.</p><a href="#" class="btn btn-light btn-lg">Learn More</a></div></section>' },
            { id: 'jumbotron', name: 'Jumbotron', icon: 'bi-window', html: '<div class="bg-light py-5"><div class="container py-4"><div class="p-5 bg-white rounded-3 shadow-sm"><h1 class="display-5 fw-bold">Custom Jumbotron</h1><p class="fs-4 text-muted">A lightweight hero component.</p><button class="btn btn-primary btn-lg">Button</button></div></div></div>' },
            { id: 'cta-section', name: 'CTA Section', icon: 'bi-megaphone', html: '<section class="bg-primary text-white py-5"><div class="container text-center"><h2 class="mb-3">Ready to get started?</h2><p class="lead mb-4">Join thousands of satisfied users today.</p><a href="#" class="btn btn-light btn-lg me-2">Sign Up Free</a><a href="#" class="btn btn-outline-light btn-lg">Contact Sales</a></div></section>' }
        ]
    },
    forms: {
        name: 'Forms', icon: 'bi-input-cursor-text',
        items: [
            { id: 'form-contact', name: 'Contact Form', icon: 'bi-envelope', html: '<div class="container py-4"><div class="row justify-content-center"><div class="col-md-6"><form><h3 class="mb-4">Contact Us</h3><div class="mb-3"><label class="form-label">Name</label><input type="text" class="form-control"></div><div class="mb-3"><label class="form-label">Email</label><input type="email" class="form-control"></div><div class="mb-3"><label class="form-label">Message</label><textarea class="form-control" rows="4"></textarea></div><button type="submit" class="btn btn-primary">Send</button></form></div></div></div>' },
            { id: 'form-login', name: 'Login Form', icon: 'bi-box-arrow-in-right', html: '<div class="container py-5"><div class="row justify-content-center"><div class="col-md-4"><div class="card shadow"><div class="card-body p-4"><h4 class="text-center mb-4">Sign In</h4><form><div class="mb-3"><label class="form-label">Email</label><input type="email" class="form-control"></div><div class="mb-3"><label class="form-label">Password</label><input type="password" class="form-control"></div><div class="mb-3 form-check"><input type="checkbox" class="form-check-input" id="remember"><label class="form-check-label" for="remember">Remember me</label></div><button type="submit" class="btn btn-primary w-100">Login</button></form></div></div></div></div></div>' },
            { id: 'form-register', name: 'Register Form', icon: 'bi-person-plus', html: '<div class="container py-5"><div class="row justify-content-center"><div class="col-md-5"><div class="card shadow"><div class="card-body p-4"><h4 class="text-center mb-4">Create Account</h4><form><div class="row"><div class="col-md-6 mb-3"><label class="form-label">First Name</label><input type="text" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Last Name</label><input type="text" class="form-control"></div></div><div class="mb-3"><label class="form-label">Email</label><input type="email" class="form-control"></div><div class="mb-3"><label class="form-label">Password</label><input type="password" class="form-control"></div><div class="mb-3 form-check"><input type="checkbox" class="form-check-input" id="terms"><label class="form-check-label" for="terms">I agree to Terms</label></div><button type="submit" class="btn btn-primary w-100">Register</button></form></div></div></div></div></div>' },
            { id: 'form-newsletter', name: 'Newsletter', icon: 'bi-newspaper', html: '<div class="bg-light py-5"><div class="container text-center"><div class="row justify-content-center"><div class="col-lg-6"><h3 class="mb-3">Subscribe</h3><p class="text-muted mb-4">Get updates straight to your inbox.</p><form class="d-flex gap-2"><input type="email" class="form-control" placeholder="Email"><button type="submit" class="btn btn-primary">Subscribe</button></form></div></div></div></div>' },
            { id: 'form-search', name: 'Search Form', icon: 'bi-search', html: '<div class="container py-3"><form class="d-flex" role="search"><input class="form-control me-2" type="search" placeholder="Search..."><button class="btn btn-outline-primary" type="submit">Search</button></form></div>' },
            { id: 'input-text', name: 'Text Input', icon: 'bi-input-cursor', html: '<div class="container py-3"><div class="mb-3"><label class="form-label">Text Input</label><input type="text" class="form-control" placeholder="Enter text"></div></div>' },
            { id: 'input-email', name: 'Email Input', icon: 'bi-at', html: '<div class="container py-3"><div class="mb-3"><label class="form-label">Email address</label><input type="email" class="form-control" placeholder="name@example.com"><div class="form-text">We will never share your email.</div></div></div>' },
            { id: 'input-password', name: 'Password Input', icon: 'bi-key', html: '<div class="container py-3"><div class="mb-3"><label class="form-label">Password</label><input type="password" class="form-control"></div></div>' },
            { id: 'textarea', name: 'Textarea', icon: 'bi-textarea-t', html: '<div class="container py-3"><div class="mb-3"><label class="form-label">Message</label><textarea class="form-control" rows="3"></textarea></div></div>' },
            { id: 'select', name: 'Select', icon: 'bi-menu-down', html: '<div class="container py-3"><div class="mb-3"><label class="form-label">Select Option</label><select class="form-select"><option selected>Choose...</option><option value="1">Option One</option><option value="2">Option Two</option><option value="3">Option Three</option></select></div></div>' },
            { id: 'checkbox', name: 'Checkboxes', icon: 'bi-check-square', html: '<div class="container py-3"><div class="form-check"><input class="form-check-input" type="checkbox" id="check1"><label class="form-check-label" for="check1">Option One</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="check2"><label class="form-check-label" for="check2">Option Two</label></div></div>' },
            { id: 'radio', name: 'Radio Buttons', icon: 'bi-record-circle', html: '<div class="container py-3"><div class="form-check"><input class="form-check-input" type="radio" name="radio" id="radio1" checked><label class="form-check-label" for="radio1">Option One</label></div><div class="form-check"><input class="form-check-input" type="radio" name="radio" id="radio2"><label class="form-check-label" for="radio2">Option Two</label></div></div>' },
            { id: 'switch', name: 'Switch', icon: 'bi-toggle-on', html: '<div class="container py-3"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="switch1"><label class="form-check-label" for="switch1">Toggle switch</label></div></div>' },
            { id: 'range', name: 'Range Slider', icon: 'bi-sliders', html: '<div class="container py-3"><label class="form-label">Range Slider</label><input type="range" class="form-range"></div>' },
            { id: 'input-group', name: 'Input Group', icon: 'bi-at', html: '<div class="container py-3"><div class="input-group mb-3"><span class="input-group-text">@</span><input type="text" class="form-control" placeholder="Username"></div><div class="input-group"><input type="text" class="form-control" placeholder="Search"><button class="btn btn-primary">Go</button></div></div>' },
            { id: 'floating-labels', name: 'Floating Labels', icon: 'bi-card-text', html: '<div class="container py-3"><div class="form-floating mb-3"><input type="email" class="form-control" id="floatEmail" placeholder="name@example.com"><label for="floatEmail">Email address</label></div><div class="form-floating"><input type="password" class="form-control" id="floatPass" placeholder="Password"><label for="floatPass">Password</label></div></div>' }
        ]
    },
    components: {
        name: 'Components', icon: 'bi-puzzle',
        items: [
            { id: 'alert-success', name: 'Alert Success', icon: 'bi-check-circle', html: '<div class="container py-3"><div class="alert alert-success alert-dismissible fade show"><strong>Success!</strong> Action completed.<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div></div>' },
            { id: 'alert-danger', name: 'Alert Danger', icon: 'bi-x-circle', html: '<div class="container py-3"><div class="alert alert-danger alert-dismissible fade show"><strong>Error!</strong> Something went wrong.<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div></div>' },
            { id: 'alert-warning', name: 'Alert Warning', icon: 'bi-exclamation-triangle', html: '<div class="container py-3"><div class="alert alert-warning alert-dismissible fade show"><strong>Warning!</strong> Please check this.<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div></div>' },
            { id: 'alert-info', name: 'Alert Info', icon: 'bi-info-circle', html: '<div class="container py-3"><div class="alert alert-info alert-dismissible fade show"><strong>Info!</strong> Here is some information.<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div></div>' },
            { id: 'buttons', name: 'Buttons', icon: 'bi-hand-index', html: '<div class="container py-3"><button class="btn btn-primary me-2">Primary</button><button class="btn btn-secondary me-2">Secondary</button><button class="btn btn-success me-2">Success</button><button class="btn btn-danger me-2">Danger</button><button class="btn btn-warning me-2">Warning</button><button class="btn btn-info">Info</button></div>' },
            { id: 'buttons-outline', name: 'Outline Buttons', icon: 'bi-square', html: '<div class="container py-3"><button class="btn btn-outline-primary me-2">Primary</button><button class="btn btn-outline-secondary me-2">Secondary</button><button class="btn btn-outline-success me-2">Success</button><button class="btn btn-outline-danger">Danger</button></div>' },
            { id: 'button-group', name: 'Button Group', icon: 'bi-ui-radios', html: '<div class="container py-3"><div class="btn-group" role="group"><button type="button" class="btn btn-primary">Left</button><button type="button" class="btn btn-primary">Middle</button><button type="button" class="btn btn-primary">Right</button></div></div>' },
            { id: 'button-toolbar', name: 'Button Toolbar', icon: 'bi-ui-checks-grid', html: '<div class="container py-3"><div class="btn-toolbar"><div class="btn-group me-2"><button type="button" class="btn btn-primary">1</button><button type="button" class="btn btn-primary">2</button><button type="button" class="btn btn-primary">3</button></div><div class="btn-group"><button type="button" class="btn btn-secondary">4</button><button type="button" class="btn btn-secondary">5</button></div></div></div>' },
            { id: 'badge', name: 'Badges', icon: 'bi-award', html: '<div class="container py-3"><span class="badge bg-primary me-1">Primary</span><span class="badge bg-success me-1">Success</span><span class="badge bg-danger me-1">Danger</span><span class="badge bg-warning text-dark me-1">Warning</span><span class="badge rounded-pill bg-info">Pill</span></div>' },
            { id: 'accordion', name: 'Accordion', icon: 'bi-chevron-expand', html: '<div class="container py-4"><div class="accordion" id="acc1"><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#c1">Item #1</button></h2><div id="c1" class="accordion-collapse collapse show" data-bs-parent="#acc1"><div class="accordion-body">Content for item 1.</div></div></div><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#c2">Item #2</button></h2><div id="c2" class="accordion-collapse collapse" data-bs-parent="#acc1"><div class="accordion-body">Content for item 2.</div></div></div></div></div>' },
            { id: 'progress', name: 'Progress Bar', icon: 'bi-bar-chart', html: '<div class="container py-3"><div class="progress mb-3"><div class="progress-bar" style="width: 25%">25%</div></div><div class="progress mb-3"><div class="progress-bar bg-success" style="width: 50%">50%</div></div><div class="progress"><div class="progress-bar bg-info" style="width: 75%">75%</div></div></div>' },
            { id: 'progress-striped', name: 'Progress Striped', icon: 'bi-bar-chart-line', html: '<div class="container py-3"><div class="progress"><div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 75%">Loading...</div></div></div>' },
            { id: 'spinner', name: 'Spinners', icon: 'bi-arrow-repeat', html: '<div class="container py-3"><div class="spinner-border text-primary me-2"></div><div class="spinner-border text-success me-2"></div><div class="spinner-grow text-warning me-2"></div><div class="spinner-grow text-danger"></div></div>' },
            { id: 'spinner-button', name: 'Spinner Button', icon: 'bi-arrow-clockwise', html: '<div class="container py-3"><button class="btn btn-primary" type="button" disabled><span class="spinner-border spinner-border-sm me-2"></span>Loading...</button></div>' },
            { id: 'list-group', name: 'List Group', icon: 'bi-list-ul', html: '<div class="container py-3"><ul class="list-group" style="max-width: 400px;"><li class="list-group-item d-flex justify-content-between">Item 1<span class="badge bg-primary rounded-pill">14</span></li><li class="list-group-item d-flex justify-content-between">Item 2<span class="badge bg-primary rounded-pill">2</span></li><li class="list-group-item d-flex justify-content-between">Item 3<span class="badge bg-primary rounded-pill">1</span></li></ul></div>' },
            { id: 'list-group-flush', name: 'List Group Flush', icon: 'bi-list-task', html: '<div class="container py-3"><ul class="list-group list-group-flush" style="max-width: 400px;"><li class="list-group-item">Item one</li><li class="list-group-item">Item two</li><li class="list-group-item">Item three</li></ul></div>' },
            { id: 'dropdown', name: 'Dropdown', icon: 'bi-caret-down', html: '<div class="container py-3"><div class="dropdown"><button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">Dropdown</button><ul class="dropdown-menu"><li><a class="dropdown-item" href="#">Action</a></li><li><a class="dropdown-item" href="#">Another action</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item" href="#">Something else</a></li></ul></div></div>' },
            { id: 'collapse', name: 'Collapse', icon: 'bi-arrows-collapse', html: '<div class="container py-3"><p><a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseEx">Toggle content</a></p><div class="collapse" id="collapseEx"><div class="card card-body">This is some placeholder content for a collapse component.</div></div></div>' },
            { id: 'modal-trigger', name: 'Modal Button', icon: 'bi-window-stack', html: '<div class="container py-3"><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Launch Modal</button><div class="modal fade" id="exampleModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Modal Title</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>Modal body text goes here.</p></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button><button type="button" class="btn btn-primary">Save</button></div></div></div></div></div>' },
            { id: 'toast', name: 'Toast', icon: 'bi-bell', html: '<div class="container py-3"><div class="toast show" role="alert"><div class="toast-header"><strong class="me-auto">Notification</strong><small>Just now</small><button type="button" class="btn-close" data-bs-dismiss="toast"></button></div><div class="toast-body">Hello! This is a toast message.</div></div></div>' },
            { id: 'offcanvas', name: 'Offcanvas', icon: 'bi-layout-sidebar', html: '<div class="container py-3"><button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasEx">Open Offcanvas</button><div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasEx"><div class="offcanvas-header"><h5 class="offcanvas-title">Offcanvas</h5><button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button></div><div class="offcanvas-body"><p>Content for the offcanvas.</p></div></div></div>' },
            { id: 'carousel', name: 'Carousel', icon: 'bi-images', html: '<div class="container py-3"><div id="carouselEx" class="carousel slide" data-bs-ride="carousel"><div class="carousel-inner"><div class="carousel-item active"><img src="https://picsum.photos/800/400/007bff/ffffff?text=Slide+1" class="d-block w-100" alt="Slide 1"></div><div class="carousel-item"><img src="https://picsum.photos/800/400/28a745/ffffff?text=Slide+2" class="d-block w-100" alt="Slide 2"></div><div class="carousel-item"><img src="https://picsum.photos/800/400/dc3545/ffffff?text=Slide+3" class="d-block w-100" alt="Slide 3"></div></div><button class="carousel-control-prev" type="button" data-bs-target="#carouselEx" data-bs-slide="prev"><span class="carousel-control-prev-icon"></span></button><button class="carousel-control-next" type="button" data-bs-target="#carouselEx" data-bs-slide="next"><span class="carousel-control-next-icon"></span></button></div></div>' },
            { id: 'placeholder', name: 'Placeholder', icon: 'bi-square-half', html: '<div class="container py-3"><div class="card" style="width: 18rem;"><div class="card-body"><h5 class="card-title placeholder-glow"><span class="placeholder col-6"></span></h5><p class="card-text placeholder-glow"><span class="placeholder col-7"></span><span class="placeholder col-4"></span><span class="placeholder col-4"></span><span class="placeholder col-6"></span></p><a class="btn btn-primary disabled placeholder col-6"></a></div></div></div>' },
            { id: 'tooltip', name: 'Tooltip', icon: 'bi-chat-square-dots', html: '<div class="container py-3"><button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" title="Tooltip text">Hover for tooltip</button></div>' },
            { id: 'popover', name: 'Popover', icon: 'bi-chat-square', html: '<div class="container py-3"><button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" title="Popover title" data-bs-content="Popover body content.">Click for popover</button></div>' },
            { id: 'close-button', name: 'Close Button', icon: 'bi-x-lg', html: '<div class="container py-3"><button type="button" class="btn-close" aria-label="Close"></button></div>' }
        ]
    },
    footer: {
        name: 'Footer', icon: 'bi-distribute-vertical',
        items: [
            { id: 'footer-simple', name: 'Footer Simple', icon: 'bi-layout-text-window-reverse', html: '<footer class="bg-dark text-white py-4"><div class="container"><div class="row align-items-center"><div class="col-md-6"><p class="mb-0">&copy; 2024 Company. All rights reserved.</p></div><div class="col-md-6 text-md-end"><a href="#" class="text-white me-3">Privacy</a><a href="#" class="text-white me-3">Terms</a><a href="#" class="text-white">Contact</a></div></div></div></footer>' },
            { id: 'footer-columns', name: 'Footer Columns', icon: 'bi-layout-sidebar-inset-reverse', html: '<footer class="bg-dark text-white pt-5 pb-4"><div class="container"><div class="row"><div class="col-lg-3 col-md-6 mb-4"><h5 class="mb-3">Company</h5><p class="text-muted">Building amazing experiences.</p></div><div class="col-lg-3 col-md-6 mb-4"><h5 class="mb-3">Links</h5><ul class="list-unstyled"><li><a href="#" class="text-muted">Home</a></li><li><a href="#" class="text-muted">About</a></li><li><a href="#" class="text-muted">Services</a></li></ul></div><div class="col-lg-3 col-md-6 mb-4"><h5 class="mb-3">Support</h5><ul class="list-unstyled"><li><a href="#" class="text-muted">FAQ</a></li><li><a href="#" class="text-muted">Help</a></li></ul></div><div class="col-lg-3 col-md-6 mb-4"><h5 class="mb-3">Newsletter</h5><form><input type="email" class="form-control mb-2" placeholder="Email"><button class="btn btn-primary w-100">Subscribe</button></form></div></div><hr class="bg-secondary"><p class="text-center text-muted mb-0">&copy; 2024 Company</p></div></footer>' },
            { id: 'footer-social', name: 'Social Footer', icon: 'bi-share', html: '<footer class="bg-light py-4"><div class="container text-center"><div class="mb-3"><a href="#" class="text-dark me-3 fs-4"><i class="bi bi-facebook"></i></a><a href="#" class="text-dark me-3 fs-4"><i class="bi bi-twitter"></i></a><a href="#" class="text-dark me-3 fs-4"><i class="bi bi-instagram"></i></a><a href="#" class="text-dark fs-4"><i class="bi bi-linkedin"></i></a></div><p class="text-muted mb-0">&copy; 2024 Company</p></div></footer>' },
            { id: 'footer-centered', name: 'Footer Centered', icon: 'bi-align-center', html: '<footer class="bg-dark text-white py-4"><div class="container text-center"><ul class="nav justify-content-center mb-3"><li class="nav-item"><a href="#" class="nav-link text-white">Home</a></li><li class="nav-item"><a href="#" class="nav-link text-white">Features</a></li><li class="nav-item"><a href="#" class="nav-link text-white">Pricing</a></li><li class="nav-item"><a href="#" class="nav-link text-white">FAQs</a></li><li class="nav-item"><a href="#" class="nav-link text-white">About</a></li></ul><p class="mb-0">&copy; 2024 Company, Inc</p></div></footer>' }
        ]
    },
    utilities: {
        name: 'Utilities', icon: 'bi-tools',
        items: [
            { id: 'spacer', name: 'Spacer', icon: 'bi-arrows-expand', html: '<div class="py-5"></div>' },
            { id: 'bg-primary', name: 'BG Primary', icon: 'bi-paint-bucket', html: '<div class="bg-primary text-white p-4"><div class="container">Primary Background Section</div></div>' },
            { id: 'bg-secondary', name: 'BG Secondary', icon: 'bi-paint-bucket', html: '<div class="bg-secondary text-white p-4"><div class="container">Secondary Background Section</div></div>' },
            { id: 'bg-dark', name: 'BG Dark', icon: 'bi-paint-bucket', html: '<div class="bg-dark text-white p-4"><div class="container">Dark Background Section</div></div>' },
            { id: 'bg-light', name: 'BG Light', icon: 'bi-paint-bucket', html: '<div class="bg-light p-4"><div class="container">Light Background Section</div></div>' },
            { id: 'bg-gradient', name: 'BG Gradient', icon: 'bi-palette', html: '<div class="bg-primary bg-gradient text-white p-4"><div class="container">Gradient Background Section</div></div>' },
            { id: 'shadow', name: 'Shadow Box', icon: 'bi-box', html: '<div class="container py-3"><div class="shadow p-3 mb-5 bg-body rounded">Shadow box</div></div>' },
            { id: 'rounded', name: 'Rounded Box', icon: 'bi-app', html: '<div class="container py-3"><div class="border rounded-3 p-4 bg-light">Rounded box with border</div></div>' },
            { id: 'text-center', name: 'Centered Text', icon: 'bi-text-center', html: '<div class="container py-3 text-center"><h3>Centered Heading</h3><p>This text is centered.</p></div>' },
            { id: 'ratio-16x9', name: 'Video Embed', icon: 'bi-play-btn', html: '<div class="container py-3"><div class="ratio ratio-16x9"><iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Video" allowfullscreen></iframe></div></div>' },
            { id: 'visually-hidden', name: 'Screen Reader', icon: 'bi-eye-slash', html: '<div class="container py-3"><p>Visible content</p><p class="visually-hidden">This content is only for screen readers</p></div>' }
        ]
    },
    links: {
        name: 'Links & Buttons', icon: 'bi-link-45deg',
        items: [
            { id: 'link-basic', name: 'Basic Link', icon: 'bi-link', html: '<div class="container py-3"><a href="#" class="link-primary">Click here to learn more</a></div>' },
            { id: 'link-secondary', name: 'Secondary Link', icon: 'bi-link', html: '<div class="container py-3"><a href="#" class="link-secondary">Secondary link</a></div>' },
            { id: 'link-success', name: 'Success Link', icon: 'bi-link', html: '<div class="container py-3"><a href="#" class="link-success">Success link</a></div>' },
            { id: 'link-danger', name: 'Danger Link', icon: 'bi-link', html: '<div class="container py-3"><a href="#" class="link-danger">Danger link</a></div>' },
            { id: 'link-underline', name: 'Underline Link', icon: 'bi-link', html: '<div class="container py-3"><a href="#" class="link-underline link-underline-primary">Underlined link</a></div>' },
            { id: 'link-offset', name: 'Offset Link', icon: 'bi-link', html: '<div class="container py-3"><a href="#" class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-100-hover">Hover underline link</a></div>' },
            { id: 'link-icon', name: 'Icon Link', icon: 'bi-box-arrow-up-right', html: '<div class="container py-3"><a href="#" class="icon-link"><i class="bi bi-box-arrow-up-right"></i> Link with icon</a></div>' },
            { id: 'link-stretched', name: 'Stretched Link', icon: 'bi-arrows-angle-expand', html: '<div class="container py-3"><div class="card" style="width: 18rem;"><div class="card-body"><h5 class="card-title">Card with stretched link</h5><p class="card-text">Click anywhere on this card.</p><a href="#" class="stretched-link">Go somewhere</a></div></div></div>' },
            { id: 'btn-link', name: 'Button Link', icon: 'bi-cursor', html: '<div class="container py-3"><a href="#" class="btn btn-link">Button styled link</a></div>' },
            { id: 'link-list', name: 'Link List', icon: 'bi-list-ul', html: '<div class="container py-3"><ul class="list-unstyled"><li><a href="#" class="link-primary">Home</a></li><li><a href="#" class="link-primary">About Us</a></li><li><a href="#" class="link-primary">Services</a></li><li><a href="#" class="link-primary">Contact</a></li></ul></div>' },
            { id: 'social-links', name: 'Social Links', icon: 'bi-share', html: '<div class="container py-3"><div class="d-flex gap-3"><a href="#" class="text-dark fs-4"><i class="bi bi-facebook"></i></a><a href="#" class="text-dark fs-4"><i class="bi bi-twitter-x"></i></a><a href="#" class="text-dark fs-4"><i class="bi bi-instagram"></i></a><a href="#" class="text-dark fs-4"><i class="bi bi-linkedin"></i></a><a href="#" class="text-dark fs-4"><i class="bi bi-github"></i></a></div></div>' },
            { id: 'cta-buttons', name: 'CTA Buttons', icon: 'bi-hand-index', html: '<div class="container py-3"><div class="d-flex gap-2"><a href="#" class="btn btn-primary btn-lg">Get Started</a><a href="#" class="btn btn-outline-secondary btn-lg">Learn More</a></div></div>' },
            { id: 'anchor-link', name: 'Anchor Link', icon: 'bi-hash', html: '<div class="container py-3"><a href="#section1" class="btn btn-outline-primary">Jump to Section</a></div>' },
            { id: 'download-link', name: 'Download Link', icon: 'bi-download', html: '<div class="container py-3"><a href="#" class="btn btn-success" download><i class="bi bi-download me-2"></i>Download File</a></div>' },
            { id: 'email-link', name: 'Email Link', icon: 'bi-envelope', html: '<div class="container py-3"><a href="mailto:example@email.com" class="btn btn-info text-white"><i class="bi bi-envelope me-2"></i>Email Us</a></div>' },
            { id: 'phone-link', name: 'Phone Link', icon: 'bi-telephone', html: '<div class="container py-3"><a href="tel:+1234567890" class="btn btn-success"><i class="bi bi-telephone me-2"></i>Call Now</a></div>' }
        ]
    },
    scrollable: {
        name: 'Scrollable', icon: 'bi-arrows-vertical',
        items: [
            { id: 'scroll-container', name: 'Scroll Container', icon: 'bi-box', html: '<div class="container py-3"><div class="overflow-auto p-3 bg-light border rounded" style="max-height: 200px;"><p>Scrollable content area. Add more content here to enable scrolling.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p><p>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit.</p><p>Excepteur sint occaecat cupidatat non proident.</p></div></div>' },
            { id: 'scroll-x', name: 'Horizontal Scroll', icon: 'bi-arrows', html: '<div class="container py-3"><div class="overflow-x-auto bg-light border rounded p-3"><div class="d-flex gap-3" style="width: max-content;"><div class="p-4 bg-primary text-white rounded">Item 1</div><div class="p-4 bg-success text-white rounded">Item 2</div><div class="p-4 bg-info text-white rounded">Item 3</div><div class="p-4 bg-warning rounded">Item 4</div><div class="p-4 bg-danger text-white rounded">Item 5</div><div class="p-4 bg-secondary text-white rounded">Item 6</div></div></div></div>' },
            { id: 'scroll-spy', name: 'Scroll Spy Nav', icon: 'bi-list-nested', html: '<div class="container py-3"><nav id="navbar-example" class="navbar bg-light px-3 mb-3 rounded"><ul class="nav nav-pills"><li class="nav-item"><a class="nav-link" href="#scrollItem1">Section 1</a></li><li class="nav-item"><a class="nav-link" href="#scrollItem2">Section 2</a></li><li class="nav-item"><a class="nav-link" href="#scrollItem3">Section 3</a></li></ul></nav></div>' },
            { id: 'sticky-top', name: 'Sticky Top', icon: 'bi-pin-angle', html: '<div class="sticky-top bg-dark text-white py-2"><div class="container"><strong>Sticky Header - Stays at top when scrolling</strong></div></div>' },
            { id: 'sticky-bottom', name: 'Sticky Bottom', icon: 'bi-pin-angle-fill', html: '<div class="sticky-bottom bg-primary text-white py-3"><div class="container text-center"><a href="#" class="btn btn-light">Sticky Call-to-Action</a></div></div>' },
            { id: 'fixed-bottom', name: 'Fixed Bottom', icon: 'bi-arrow-down-square', html: '<div class="container py-3"><div class="alert alert-info">Note: Fixed elements will be positioned relative in the builder, but fixed in preview/download.</div><div class="bg-dark text-white py-3 text-center rounded"><div class="container">Fixed Bottom Bar</div></div></div>' },
            { id: 'scroll-cards', name: 'Scrollable Cards', icon: 'bi-collection', html: '<div class="container py-3"><div class="d-flex overflow-auto gap-3 pb-3"><div class="card flex-shrink-0" style="width: 250px;"><img src="https://picsum.photos/250/150" class="card-img-top" alt="Card"><div class="card-body"><h6 class="card-title">Card 1</h6></div></div><div class="card flex-shrink-0" style="width: 250px;"><img src="https://picsum.photos/250/150" class="card-img-top" alt="Card"><div class="card-body"><h6 class="card-title">Card 2</h6></div></div><div class="card flex-shrink-0" style="width: 250px;"><img src="https://picsum.photos/250/150" class="card-img-top" alt="Card"><div class="card-body"><h6 class="card-title">Card 3</h6></div></div><div class="card flex-shrink-0" style="width: 250px;"><img src="https://picsum.photos/250/150" class="card-img-top" alt="Card"><div class="card-body"><h6 class="card-title">Card 4</h6></div></div></div></div>' },
            { id: 'back-to-top', name: 'Back to Top', icon: 'bi-arrow-up-circle', html: '<div class="container py-3 text-center"><a href="#top" class="btn btn-outline-primary"><i class="bi bi-arrow-up me-2"></i>Back to Top</a></div>' }
        ]
    },
    premadeStyles: {
        name: 'Premade Styles', icon: 'bi-palette2',
        items: [
            { id: 'style-modern-hero', name: 'Modern Hero', icon: 'bi-star', html: '<section style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);" class="py-5"><div class="container py-5"><div class="row align-items-center"><div class="col-lg-6 text-white"><h1 class="display-4 fw-bold mb-4">Innovative Solutions</h1><p class="lead mb-4 opacity-75">Transform your business with cutting-edge technology and expert guidance.</p><div class="d-flex gap-3"><a href="#" class="btn btn-light btn-lg px-4">Get Started</a><a href="#" class="btn btn-outline-light btn-lg px-4">Watch Demo</a></div></div><div class="col-lg-6"><img src="https://picsum.photos/500/400" class="img-fluid rounded-4 shadow-lg" alt="Hero"></div></div></div></section>' },
            { id: 'style-dark-hero', name: 'Dark Hero', icon: 'bi-moon-stars', html: '<section class="py-5" style="background: linear-gradient(180deg, #1a1a2e 0%, #16213e 100%);"><div class="container py-5 text-center"><h1 class="display-3 fw-bold text-white mb-4">Build. Ship. Scale.</h1><p class="lead text-white-50 mb-5 mx-auto" style="max-width: 600px;">The modern platform for ambitious developers and businesses.</p><div class="d-flex gap-3 justify-content-center"><a href="#" class="btn btn-primary btn-lg px-5">Start Free Trial</a><a href="#" class="btn btn-outline-light btn-lg px-5">View Pricing</a></div></div></section>' },
            { id: 'style-glass-card', name: 'Glass Card', icon: 'bi-transparency', html: '<div class="container py-5"><div class="p-5 rounded-4 text-white" style="background: rgba(255,255,255,0.1); backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.2);"><h3 class="mb-3">Glassmorphism Card</h3><p class="opacity-75">A modern glass-like effect with blur and transparency. Works best on colored backgrounds.</p><a href="#" class="btn btn-light">Learn More</a></div></div>' },
            { id: 'style-gradient-card', name: 'Gradient Card', icon: 'bi-palette-fill', html: '<div class="container py-4"><div class="card border-0 rounded-4 overflow-hidden shadow-lg"><div class="p-5" style="background: linear-gradient(45deg, #f093fb 0%, #f5576c 100%);"><h3 class="text-white mb-3">Premium Feature</h3><p class="text-white opacity-75">Unlock exclusive features with our premium plan.</p><a href="#" class="btn btn-light btn-lg">Upgrade Now</a></div></div></div>' },
            { id: 'style-feature-grid', name: 'Feature Grid', icon: 'bi-grid-3x3-gap', html: '<section class="py-5 bg-light"><div class="container"><div class="text-center mb-5"><h2 class="fw-bold">Why Choose Us</h2><p class="text-muted">Everything you need to succeed</p></div><div class="row g-4"><div class="col-md-4"><div class="text-center p-4"><div class="bg-primary bg-gradient rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style="width:64px;height:64px;"><i class="bi bi-lightning-charge text-white fs-4"></i></div><h5>Lightning Fast</h5><p class="text-muted">Optimized for speed and performance.</p></div></div><div class="col-md-4"><div class="text-center p-4"><div class="bg-success bg-gradient rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style="width:64px;height:64px;"><i class="bi bi-shield-check text-white fs-4"></i></div><h5>Secure</h5><p class="text-muted">Enterprise-grade security built in.</p></div></div><div class="col-md-4"><div class="text-center p-4"><div class="bg-info bg-gradient rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style="width:64px;height:64px;"><i class="bi bi-headset text-white fs-4"></i></div><h5>24/7 Support</h5><p class="text-muted">Round-the-clock expert assistance.</p></div></div></div></div></section>' },
            { id: 'style-pricing', name: 'Pricing Table', icon: 'bi-currency-dollar', html: '<section class="py-5"><div class="container"><div class="text-center mb-5"><h2 class="fw-bold">Simple Pricing</h2><p class="text-muted">Choose the plan that fits your needs</p></div><div class="row g-4 justify-content-center"><div class="col-lg-4"><div class="card h-100 shadow-sm"><div class="card-body p-4"><h5 class="text-muted">Starter</h5><h2 class="fw-bold">$9<small class="text-muted fw-normal">/mo</small></h2><hr><ul class="list-unstyled"><li class="mb-2"><i class="bi bi-check text-success me-2"></i>5 Projects</li><li class="mb-2"><i class="bi bi-check text-success me-2"></i>Basic Support</li><li class="mb-2"><i class="bi bi-check text-success me-2"></i>1GB Storage</li></ul><a href="#" class="btn btn-outline-primary w-100">Get Started</a></div></div></div><div class="col-lg-4"><div class="card h-100 shadow border-primary"><div class="card-body p-4"><span class="badge bg-primary mb-2">Popular</span><h5 class="text-muted">Pro</h5><h2 class="fw-bold">$29<small class="text-muted fw-normal">/mo</small></h2><hr><ul class="list-unstyled"><li class="mb-2"><i class="bi bi-check text-success me-2"></i>Unlimited Projects</li><li class="mb-2"><i class="bi bi-check text-success me-2"></i>Priority Support</li><li class="mb-2"><i class="bi bi-check text-success me-2"></i>10GB Storage</li></ul><a href="#" class="btn btn-primary w-100">Get Started</a></div></div></div></div></div></section>' },
            { id: 'style-testimonial', name: 'Testimonial', icon: 'bi-chat-quote', html: '<section class="py-5 bg-light"><div class="container"><div class="row justify-content-center"><div class="col-lg-8"><div class="text-center"><i class="bi bi-quote fs-1 text-primary opacity-25"></i><blockquote class="blockquote fs-4 my-4">"This platform transformed our workflow. We increased productivity by 300% in just two months."</blockquote><div class="d-flex align-items-center justify-content-center gap-3"><img src="https://picsum.photos/60/60" class="rounded-circle" alt="Avatar"><div class="text-start"><strong>John Smith</strong><p class="text-muted mb-0">CEO, TechCorp</p></div></div></div></div></div></div></section>' },
            { id: 'style-stats', name: 'Stats Section', icon: 'bi-graph-up', html: '<section class="py-5 bg-primary text-white"><div class="container"><div class="row text-center g-4"><div class="col-md-3"><h2 class="display-4 fw-bold">500+</h2><p class="mb-0 opacity-75">Happy Clients</p></div><div class="col-md-3"><h2 class="display-4 fw-bold">1.2M</h2><p class="mb-0 opacity-75">Downloads</p></div><div class="col-md-3"><h2 class="display-4 fw-bold">99%</h2><p class="mb-0 opacity-75">Satisfaction</p></div><div class="col-md-3"><h2 class="display-4 fw-bold">24/7</h2><p class="mb-0 opacity-75">Support</p></div></div></div></section>' },
            { id: 'style-team', name: 'Team Section', icon: 'bi-people', html: '<section class="py-5"><div class="container"><div class="text-center mb-5"><h2 class="fw-bold">Meet Our Team</h2><p class="text-muted">The people behind our success</p></div><div class="row g-4"><div class="col-md-4"><div class="text-center"><img src="https://picsum.photos/200/200" class="rounded-circle mb-3" alt="Team member"><h5 class="mb-1">Jane Doe</h5><p class="text-muted">CEO & Founder</p><div class="d-flex gap-2 justify-content-center"><a href="#" class="text-muted"><i class="bi bi-linkedin"></i></a><a href="#" class="text-muted"><i class="bi bi-twitter"></i></a></div></div></div><div class="col-md-4"><div class="text-center"><img src="https://picsum.photos/200/200" class="rounded-circle mb-3" alt="Team member"><h5 class="mb-1">John Smith</h5><p class="text-muted">CTO</p><div class="d-flex gap-2 justify-content-center"><a href="#" class="text-muted"><i class="bi bi-linkedin"></i></a><a href="#" class="text-muted"><i class="bi bi-twitter"></i></a></div></div></div><div class="col-md-4"><div class="text-center"><img src="https://picsum.photos/200/200" class="rounded-circle mb-3" alt="Team member"><h5 class="mb-1">Emily Brown</h5><p class="text-muted">Lead Designer</p><div class="d-flex gap-2 justify-content-center"><a href="#" class="text-muted"><i class="bi bi-linkedin"></i></a><a href="#" class="text-muted"><i class="bi bi-dribbble"></i></a></div></div></div></div></div></section>' },
            { id: 'style-faq', name: 'FAQ Section', icon: 'bi-question-circle', html: '<section class="py-5 bg-light"><div class="container"><div class="text-center mb-5"><h2 class="fw-bold">Frequently Asked Questions</h2></div><div class="row justify-content-center"><div class="col-lg-8"><div class="accordion" id="faqAccordion"><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faq1">How do I get started?</button></h2><div id="faq1" class="accordion-collapse collapse show" data-bs-parent="#faqAccordion"><div class="accordion-body">Simply sign up for a free account and explore our features. Our onboarding wizard will guide you through the process.</div></div></div><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq2">What payment methods do you accept?</button></h2><div id="faq2" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body">We accept all major credit cards, PayPal, and bank transfers for enterprise clients.</div></div></div><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq3">Can I cancel anytime?</button></h2><div id="faq3" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body">Yes! You can cancel your subscription at any time with no questions asked.</div></div></div></div></div></div></div></section>' },
            { id: 'style-cta-banner', name: 'CTA Banner', icon: 'bi-megaphone', html: '<section class="py-5" style="background: linear-gradient(90deg, #4facfe 0%, #00f2fe 100%);"><div class="container text-center text-white py-4"><h2 class="fw-bold mb-3">Ready to Get Started?</h2><p class="lead mb-4 opacity-75">Join thousands of satisfied customers today.</p><div class="d-flex gap-3 justify-content-center"><a href="#" class="btn btn-light btn-lg px-5">Start Free Trial</a><a href="#" class="btn btn-outline-light btn-lg px-5">Contact Sales</a></div></div></section>' }
        ]
    }
};

